# this is the basic workflow

name: CI 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      - name: add remote link
        env:
          HF: ${{secrets.HF}}
        run: git remote add space https://harishkumarshivaramappa:$HF@huggingface.co/spaces/harishkumarshivaramappa/demo
      - name: push to hub 
        env:
          HF: ${{secrets.HF}}
        run: git push --force https://harishkumarshivaramappa:$HF@huggingface.co/spaces/harishkumarshivaramappa/demo main
          
          
